N = 1;
R = E = 2;
S = 3;
L = W = 4;

walls = [ ...
    horizontal( 01 ), ...
    vertical(   02 ), ...
    horizontal( 03 ), ...
    vertical(   04 ), ...
    horizontal( 05 ), ...
    vertical(   06 ), ...
    horizontal( 07 ), ...
    vertical(   08 ), ...
    horizontal( 09 ), ...
    horizontal( 10 ), ...
    vertical(   11 ), ...
    horizontal( 12 ), ...
    vertical(   13 )];

constraints = [ ...
    origin(    walls, 01, L); ...
    thickness( walls, 01, .25 ); ...
    thickness( walls, 02, .25 ); ...
    thickness( walls, 03, .25 ); ...
    thickness( walls, 04, .25 ); ...
    thickness( walls, 05, .25 ); ...
    thickness( walls, 06, .25 ); ...
    thickness( walls, 07, .25 ); ...
    thickness( walls, 08, .25 ); ...
    thickness( walls, 10, .10 ); ...
    thickness( walls, 11, .25 ); ...
    thickness( walls, 12, .25 ); ...
    thickness( walls, 13, .25 ); ...
    ... % Connections
    connect(   walls, 01, R, 02, N); ...
    connect(   walls, 02, S, 03, L); ...
    connect(   walls, 03, R, 04, S); ...
    connect(   walls, 04, N, 05, L); ...
    connect(   walls, 05, R, 06, N); ...
    connect(   walls, 06, S, 07, L); ...
    connect(   walls, 07, R, 08, N); ...
    connect(   walls, 08, S, 09, R); ...
    connect(   walls, 10, L, 11, S); ...
    connect(   walls, 11, N, 12, L); ...
    connect(   walls, 12, R, 13, S); ...
    connect(   walls, 13, N, 01, L); ...
    ... % Alignments
    distance(  walls, 01, S, 05, S, 0.00); ...
    distance(  walls, 12, S, 03, S, 0.00); ...
    distance(  walls, 03, S, 07, S, 0.00); ...
    distance(  walls, 10, S, 09, S, 0.00); ...
    distance(  walls, 10, R, 09, L, 0.00); ...
    ... % Distances
    distance(  walls, 01, S, 10, N, 4.50); ...
    distance(  walls, 12, S, 10, N, 4.50 - 0.85); ...
    distance(  walls, 11, R, 08, L, 5.98 + 0.10 + 3.75); ...
    distance(  walls, 05, S, 09, N, 4.32); ...
    distance(  walls, 13, R, 02, L, 2.60); ...
    distance(  walls, 11, R, 13, R, 0.75); ...
    distance(  walls, 04, R, 06, L, 2.60); ...
    distance(  walls, 06, L, 08, L, 0.75); ...
    distance(  walls, 09, L, 08, L, 2.00); ...
    ];

% equal_thinkness()

constraints_M = constraints(:, 1:end-1);
constraints_v = constraints(:, end);

raw_sol = constraints_M \ constraints_v;
sol     = reshape(raw_sol, 4, size(raw_sol, 1) / 4)';
rects   = draw_plan(walls, sol);

% Finding over constrained stuff:
% raw_errors = constraints_M * raw_sol - constraints_v;
% i = find(abs(raw_errors) > .01)
% constraints_M(i, :)
